name: Reserve Slot

on:
  schedule:
    - cron: "0 8 * * *" # Use "0 8 * * SUN,TUE,FRI" to only reserve for the next day like Monday, Wednesday and Saturday.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cypress-io/github-action@v5
      with:
        browser: chrome
      env:
        CYPRESS_ELEMENTS_EMAIL: ${{ secrets.ELEMENTS_EMAIL }}
        CYPRESS_ELEMENTS_PASSWORD: ${{ secrets.ELEMENTS_PASSWORD }}


    - name: Upload Artifact For Reservation Proof
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: slot-reserved
        path: cypress/screenshots/reserve.cy.js/slot-reserved.png
        retention-days: 3

    - name: Upload Artifact For Reservation Failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-available.mp4
        path: cypress/videos/reserve.cy.js.mp4
        retention-days: 2
