name: Check Appointment

on:
  schedule:
    - cron: "* 12 * * SUN,TUE,FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./reserve-next-slot.sh
      env:
        ELEMENTS_EMAIL: ${{ secrets.ELEMENTS_EMAIL }}
        ELEMENTS_PASSWORD: ${{ secrets.ELEMENTS_PASSWORD }}