name: Reserve Slot

on:
  schedule:
    - cron: "0 12 * * SUN,TUE,FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cypress-io/github-action@v5
      with:
        browser: chrome
        headless: true
      env:
        CYPRESS_ELEMENTS_EMAIL: ${{ secrets.ELEMENTS_EMAIL }}
        CYPRESS_ELEMENTS_PASSWORD: ${{ secrets.ELEMENTS_PASSWORD }}

    - name: Upload Artifact For Reservation Proof
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: appointment-available.mp4
        path: cypress/videos/reserve.cy.js.mp4
        retention-days: 2
